# Generated by Django 5.1.3 on 2024-11-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_create_author', 'Permission to create new author instances'), ('can_delete_author', 'Permission to delete a author instance')]},
        ),
    ]
